import React, { useMemo, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { createRuntime, type Runtime } from './services/runtime';
import { useHealthLoop } from './services/use-healthloop';
import { Consents, Home, Login, Missions, Points, Profile } from './screens/main';
import { Button, Card, Copy, Title } from './components/ui';
import { t } from './i18n';
import { theme } from './theme';
const tabs = [{key:'home',glyph:'◉'},{key:'missions',glyph:'✓'},{key:'points',glyph:'◇'},{key:'profile',glyph:'○'}] as const;
function Application({runtime}:{runtime:Runtime}) {
  const state=useHealthLoop(runtime);const [tab,setTab]=useState<typeof tabs[number]['key']>('home');
  const ready=!!state.session&&state.consented;
  return <SafeAreaView style={styles.container}><StatusBar style="dark"/><View style={styles.header}><View><Text style={styles.wordmark}>{t('brand')}</Text><Text style={styles.eyebrow}>{t('eyebrow')}</Text></View><View style={styles.brandIcon}><Text style={{color:'#fff',fontSize:24}}>↗</Text></View></View><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView key={tab} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">{!!state.message&&<View accessibilityRole="alert" accessibilityLiveRegion="polite" style={styles.notice}><Copy>{state.message}</Copy></View>}{state.session&&state.connection==='offline'&&<Card tint><Title>{t('offlineLocal')}</Title><Copy>{state.consented?t('offlineLocalBody'):t('offlineUnconfirmed')}</Copy><Button secondary label={t('reconnect')} onPress={state.reconnect} busy={state.busy}/></Card>}{state.session&&state.connection==='verifying'&&<Copy muted>{t('verifyingConsent')}</Copy>}{state.loading?<View style={{padding:40,gap:20}}><ActivityIndicator color={theme.primary}/><Copy>{t('load')}</Copy></View>:!state.session?<Login state={state}/>:state.connection==='blocked'?<Card><Title>{t('accessBlocked')}</Title><Copy>{t('accessBlockedBody')}</Copy><Button label={t('reconnect')} onPress={state.reconnect} busy={state.busy}/><Button secondary label={t('logout')} onPress={state.logout} busy={state.busy}/></Card>:!state.consented?<Consents state={state}/>:tab==='home'?<Home state={state}/>:tab==='missions'?<Missions state={state}/>:tab==='points'?<Points state={state}/>:<Profile state={state}/>}</ScrollView></KeyboardAvoidingView>{ready&&<View style={styles.nav}>{tabs.map(item=><Pressable key={item.key} accessibilityRole="tab" accessibilityLabel={t(item.key)} accessibilityState={{selected:tab===item.key}} onPress={()=>setTab(item.key)} style={[styles.tab,tab===item.key&&styles.selected]}><Text style={[styles.tabGlyph,tab===item.key&&styles.activeText]}>{item.glyph}</Text><Text style={[styles.tabLabel,tab===item.key&&styles.activeText]}>{t(item.key)}</Text></Pressable>)}</View>}</SafeAreaView>;
}
export default function App(){const runtime=useMemo(()=>{try{return createRuntime()}catch{return null}},[]);return <SafeAreaProvider>{runtime?<Application runtime={runtime}/>:<SafeAreaView style={styles.container}><View style={styles.content}><Card><Title>{t('configTitle')}</Title><Copy>{t('configBody')}</Copy></Card></View></SafeAreaView>}</SafeAreaProvider>}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:theme.bg},header:{paddingHorizontal:24,paddingVertical:16,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},wordmark:{fontSize:23,fontWeight:'700',color:theme.ink,letterSpacing:2},eyebrow:{fontSize:9,letterSpacing:1.1,color:theme.muted,marginTop:7},brandIcon:{width:44,height:44,borderRadius:16,backgroundColor:theme.primary,alignItems:'center',justifyContent:'center'},content:{padding:20,paddingTop:10,paddingBottom:32,gap:20},notice:{padding:16,borderRadius:16,backgroundColor:'#FFF1D9',borderColor:'#EFDCB7',borderWidth:1},nav:{flexDirection:'row',gap:5,paddingHorizontal:12,paddingTop:10,paddingBottom:9,backgroundColor:'#fff',borderTopColor:theme.line,borderTopWidth:1},tab:{flex:1,alignItems:'center',paddingVertical:10,paddingHorizontal:4,borderRadius:16,gap:3,minHeight:60},selected:{backgroundColor:theme.pale},tabGlyph:{color:theme.muted,fontSize:24,lineHeight:26},tabLabel:{color:theme.muted,fontSize:12,lineHeight:18,textAlign:'center'},activeText:{color:theme.primary,fontWeight:'700'}});
