export const zh = {
  reminderApiError:'提醒偏好暂时无法读取或保存。请重试；其他功能仍可使用。',
  reminderTitle:'给自己一点从容的时间', reminderBody:'按自己的节奏照顾日常习惯。今天也可以选择休息。',
  reminderToggle:'每日习惯提醒', reminderToggleHelp:'开启后请保存，再由您决定是否允许系统通知；关闭立即停止本机提醒，保存后同步到账户。',
  reminderTime:'提醒时间', quietStart:'安静时段开始', quietEnd:'安静时段结束', reminderTimezone:'所有时间采用香港时间（Asia/Hong_Kong），包括跨午夜的安静时段。', reminderTimeHelp:'使用24小时制 HH:mm。提醒必须在安静时段以外；开始包含在安静时段内，结束时可恢复提醒。', reminderSave:'保存提醒偏好', reminderSaved:'提醒偏好已保存。实际提醒状态请查看本机状态。', reminderDraft:'尚有未保存的选择。关闭已在本机生效；重新开启须保存确认。', reminderConflict:'其他操作已更新提醒偏好。请重新读取已保存设置，再确认您的选择。', reminderReload:'读取已保存设置', reminderRefresh:'重新检查本机提醒', reminderRefreshNeeded:'请先联网读取提醒偏好。关闭本机提醒仍然可用。', reminderInvalid:'请输入有效的24小时时间；安静时段起止不能相同，开启提醒时须避开安静时段。',
  reminderOff:'本机提醒未安排', reminderScheduled:'本机已安排每日提醒', reminderBlocked:'本机通知权限尚未允许，提醒未安排', reminderScheduleError:'本机提醒未能确认，请重试或在系统设置中关闭通知。', reminderStateError:'本机提醒状态未能确认。请重试；如要停止提醒，可先在系统设置中关闭通知。', reminderDenied:'您尚未允许系统通知。App 仍可正常使用；如需提醒，可到系统设置中更改。', reminderUnavailable:'此环境不支持 iOS 本机提醒。请使用更新后的 iPhone 开发构建。', reminderSettings:'打开通知设置', reminderRetry:'重试读取偏好', reminderPendingServer:'本机已停止提醒，账户设置尚未同步；重新连接后请保存关闭选择。',

  logoutFailed:'健康读取与同步已停止，但本机登录凭据未能完整清除。请重试退出登录，完成后再登录。', retryLogout:'重试退出登录',
  offlineLocal:'离线 · 仅在本机查看', offlineLocalBody:'已恢复此前由服务器确认的本机读取选择。云端同步与领取暂停；重新连接并核实账户后才会恢复。', offlineUnconfirmed:'暂时无法核实账户。本机没有可用的已确认同意记录，健康读取与同步均暂停。', verifyingConsent:'正在重新核实账户与同意。云端操作暂时暂停。', accessBlocked:'账户或同意暂时无法确认', accessBlockedBody:'当前响应无法确认有效访问。本机读取与云端操作已停止；重新连接核实，或退出登录。', reconnect:'重新连接并核实', reconnected:'账户与同意已重新核实。您可以手动重试未完成的同步。', reconnectRequired:'请先重新连接并核实账户，再执行云端操作。', syncHistory:'补同步与重试', syncHistoryHelp:'可提交今天与前一天的最少化摘要；补同步截止由服务器判断。原始健康记录不会保存到待上传队列。', retryPending:'重试未完成的核实', syncDay:'同步此日', draftConsent:'开启选项后需保存并获得服务器确认才会启用；关闭立即生效。',

  invalidData:'读取的记录格式不完整或有冲突，暂不用于任务核实。请检查数据来源或提交更正申请。', queryError:'本机查询未完成，请重试。尚不能判断是否有可读取数据。',
  rateLimited:'操作过于频繁，请稍候再试。', rewardsPaused:'积分发放暂时暂停，历史积分仍可查看。', cutoffPassed:'该任务已超过补同步截止时间，可提交更正申请。', sourcePinned:'该日来源已固定，不能切换来源重复核实。请提交更正申请。', reauthRequired:'请重新验证邮箱后再删除账户。', sessionExpired:'登录已失效或账户已停用，请重新登录。',
  brand:'健康循环', tagline:'每一步，都照顾自己', eyebrow:'HEALTHLOOP · 日常健康习惯',
  home:'首页', missions:'任务', points:'积分与奖励', profile:'我的',
  configTitle:'先完成安全配置', configBody:'当前环境配置缺失或不匹配。请按开发文档设置真实应用环境、公开密钥与核心服务地址，再重新构建。应用尚未连接任何服务。',
  welcome:'从一个轻松的习惯开始', welcomeBody:'查看自己的活动记录，选择适合自己的目标。休息同样重要，不必追赶，也不会扣分。',
  email:'电子邮箱', emailPlaceholder:'输入您的电子邮箱', code:'邮箱验证码', codePlaceholder:'输入收到的验证码', sendCode:'发送验证码', verify:'验证并登录', resend:'重新发送', sent:'验证码已发送，请查看邮箱。', resendWait:'请稍候再重新发送验证码。', authError:'验证未完成。请检查邮箱与验证码；过期后可重新发送。', logout:'退出登录',
  privacyTitle:'由您决定数据如何使用', privacyBody:'健康循环是面向成年人的习惯工具，不提供医疗诊断或治疗。遇到疼痛或不适，请停止活动并寻求专业帮助。',
  adult:'我确认已年满18岁', localRead:'允许在本机读取健康数据', localHelp:'只读步数。不会写入或修改 Apple 健康记录。您可随时关闭。', cloudSync:'允许最少化云端同步', cloudHelp:'只同步任务日期、可计奖步数和来源规则等必要摘要。睡眠与心率留在本机。关闭后仍可查看本机数据。', marketing:'接收营销内容', marketingHelp:'可选，默认关闭。拒绝不会影响使用。健康记录不会用于广告定向。', saveConsent:'保存我的选择', consentVersion:'同意说明版本：2026-09-18', adultNeeded:'请先确认已年满18岁。', consentSaved:'已保存您的选择。', consentPending:'本机已立即停止相关读取和同步；云端设置保存失败，请重试。',
  today:'今天的活动', steps:'步', noData:'暂无可读取的数据', unknownRead:'空结果无法判断是否授予了读取权限。您可以检查“健康”App 中的数据与访问设置。', availableSteps:'可用于任务核实', goal:'我的每日目标', goalValue:'3,000 步', gentle:'按自己的节奏走，休息不会扣分。', source:'来源', sourcePhone:'Apple 手机', sourceWatch:'Apple 手表', sourceUnknown:'未知来源', sourceNone:'尚未选择', updated:'本机更新时间', notUpdated:'尚未读取', history:'最近7天', policyHelp:'每天固定一个获准来源，手机与手表不叠加。手动输入、未知来源和有重叠疑问的记录不自动计奖。', readHealth:'读取健康数据', refresh:'刷新', requestAccess:'请求步数读取访问', accessHelp:'首次使用会显示系统健康访问面板。面板完成不代表应用能获知读取授权状态。', healthSettings:'检查健康访问设置', settingsBody:'打开“健康”App → 头像 → App → 健康循环，查看允许读取的数据。您也可以在系统设置中管理健康访问。空数据不等同于拒绝授权。', settingsOpen:'打开系统设置', dismiss:'知道了', unavailable:'当前设备无法使用 HealthKit。请在安装开发构建的兼容 iPhone 上打开；浏览器与 Expo Go 不能读取健康数据。', reading:'正在读取本机数据…', sync:'同步并核实任务', syncing:'正在同步…', syncDisabled:'开启本机读取与云端同步，并取得有效来源的数据后，才可核实任务。', syncDone:'服务器已完成核实，积分页面已更新。', pendingReview:'摘要正在等待核实，暂未增加可用积分。', noNetwork:'服务暂时不可用，可能已离线。已有数据仅供查看；重试成功前不会发放积分。', stale:'这里显示的是上次读取结果。请刷新获取最新记录。',
  optional:'可选健康信息', sleep:'睡眠记录', sleepRequest:'单独开启睡眠读取', sleepHelp:'只在本机显示可读取的睡眠区间，不作为奖励目标。', heart:'最近一次心率', heartRequest:'单独开启心率读取', heartHelp:'只展示历史测量值与时间，不代表实时状态，也不作诊断。', bpm:'次/分钟', minutes:'分钟', noSleep:'暂无可读取的睡眠区间', noHeart:'暂无可读取的心率记录',
  missionTitle:'小目标，慢慢来', missionBody:'积分由服务器根据已核实的数据计算。每天只计最高档；升级只补差额。', dailyMission:'每日步行', weeklyMission:'一周里的3个活动日', dailyCap:'每日最高30积分', weeklyCap:'每周奖励最多20积分', weekHelp:'每周3个不同日期达到已固定的3,000步目标，获得20积分。星期一开始新的一周。', rule:'规则版本', deadline:'补同步截止', earned:'已获得', notInstanced:'同步有效摘要后生成任务实例。', pointsUnit:'积分', tier3:'3,000步 · 10积分', tier5:'5,000步 · 20积分', tier7:'7,000步 · 30积分',
  balance:'可用积分', pending:'待核实记录', reversed:'已退款积分', ledger:'积分流水', ledgerEmpty:'还没有积分流水。经服务器核实后，每一笔变动都会记录在这里。', pointsDisclaimer:'积分不可转让、没有现金价值，也不承诺兑换未来代币。', rewards:'徽章与示范奖励', rewardTitle:'习惯之芽 · 平台徽章', rewardBody:'奖励目录尚未开放。未来的示范券将明确标注不可使用，不代表已签约商户。', unavailableFeature:'尚未开放', more:'加载更多',
  rewardsDemoNotice:'这里仅提供平台演示奖励。演示码不可用于真实消费或核销，不代表商户合作。', rewardsEmpty:'暂无可兑换的演示奖励。', demoReward:'平台演示奖励', rewardCost:'所需积分', rewardStock:'剩余演示名额', redeem:'兑换演示奖励', redeemConfirm:'确认演示兑换', redeemConfirmBody:'将扣除 {points} 积分，生成不可真实核销的演示记录。可取消演示兑换并退回该笔积分。', cancelDialog:'暂不操作', confirmRedeem:'确认扣除积分', insufficientPoints:'可用积分不足', outOfStock:'演示名额已用完', rewardConsentNeeded:'新兑换需要已确认的云端同步同意。已生成的演示记录仍可查看和取消。', rewardRefreshNeeded:'请刷新并核实奖励目录及积分后再操作。', rewardPending:'有一笔演示操作尚未核实', rewardPendingBody:'可能已提交成功。请核实原请求，避免再次扣分；新兑换暂时暂停。', rewardRefreshPending:'服务器已返回结果，正在等待完整刷新。刷新完成前不会显示兑换成功。', retryReward:'核实原演示操作', rewardConfirmed:'演示记录、积分与目录已重新核实。请以当前记录状态为准。', refundConfirmed:'取消状态、积分与目录已重新核实。', redemptionHistory:'我的演示记录', redemptionEmpty:'还没有演示兑换记录。', demonstrationStatus:'演示中 · 不可真实核销', cancelledStatus:'已取消', demoCodeLabel:'不可核销的演示码', cancelRedemption:'取消并退回积分', cancelRedemptionConfirm:'取消这笔演示兑换？', cancelRedemptionBody:'确认后将取消演示记录，并按服务器记录退回原扣除积分。同一笔只退款一次。', confirmCancelRedemption:'确认取消并退款', refundAvailableWithoutConsent:'关闭云端同步后，仍可在账户核实通过时取消演示兑换并退款。', rewardNotFound:'该演示奖励或兑换记录已不可用，请刷新查看。', noPendingReward:'当前没有待核实的演示操作，请刷新查看记录。', correctionTotal:'更正净额', signedBalance:'账本余额', negativeBalanceHelp:'历史更正后账本余额低于零。可用积分为零，暂不能新兑换；原有演示兑换仍可取消退款。', correctionReference:'更正编号', correctionReason:'更正理由', decisionReason:'审核说明', dailyCorrection:'每日任务更正', weeklyCorrection:'每周任务更正', refund:'兑换退款', ownAppeals:'我的更正申请', appealsEmpty:'暂无更正申请。', appealOpen:'处理中', appealResolved:'已处理', proposalPending:'方案待审核', proposalApproved:'方案已通过', proposalRejected:'方案已拒绝', appealReason:'申请说明', proposalReason:'处理方案说明', correctionDetailsHelp:'更正编号对应处理方案；可在“我的更正申请”查看已加载的处理理由。',
  taskDateLabel:'任务日期', taskDatePlaceholder:'YYYY-MM-DD',
  account:'账户与隐私', preferences:'通知偏好', notifyHelp:'每日最多一次温和的本机提醒，默认关闭，不含健康读数或积分信息。拒绝通知不影响其他功能，也不需要营销或健康同步同意。', export:'导出我的数据', exportHelp:'生成个人账户与必要任务数据的 JSON 文本，通过系统分享菜单保存或发送到您选择的位置。', exportTitle:'健康循环个人数据导出', correction:'提交更正申请', correctionHelp:'说明需要更正的任务日期及原因。请勿输入原始健康记录或敏感医疗资料。', correctionPlaceholder:'例如：需要核查某日来源规则', submitCorrection:'发送更正申请', correctionSent:'更正申请已提交，等待人工处理。', delete:'删除账户', deleteHelp:'删除前需要重新验证邮箱。删除提交后将立即停用同步及积分领取，后续清除按照数据保留政策处理。', deleteSend:'发送删除验证邮件', deleteConfirm:'验证并提交删除', deleteDone:'删除请求已提交，账户已停用。', error:'操作未完成，请稍后重试。', help:'使用与隐私说明', helpBody:'本应用只读健康记录。原始睡眠与心率不会上传。关闭云端同步立即停止新上传；关闭本机读取停止查询。积分任务不鼓励过量运动。如需核查记录，请提交更正申请。', demoSponsor:'赞助内容', sponsorBody:'赞助展示功能尚未开放。健康数据不会用于广告定向；观看或点击广告不会获得积分。', load:'正在加载…', retry:'重试', success:'已完成', award:'任务奖励', adjustment:'调整或冲销', redemption:'示范兑换',
} as const;
export type TranslationKey = keyof typeof zh;
export const t = (key: TranslationKey) => zh[key];
