import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Switch, Text, TextInput, View, type TextInputProps } from 'react-native';
import { theme } from '../theme';
export function Copy({children,muted=false,large=false}:{children:React.ReactNode;muted?:boolean;large?:boolean}) {return <Text style={[styles.copy,muted&&styles.muted,large&&styles.large]}>{children}</Text>}
export function Card({children,tint=false}:{children:React.ReactNode;tint?:boolean}) {return <View style={[styles.card,tint&&styles.tint]}>{children}</View>}
export function Title({children}:{children:React.ReactNode}) {return <Text accessibilityRole="header" style={styles.title}>{children}</Text>}
export function Button({label,onPress,disabled=false,secondary=false,busy=false,danger=false}:{label:string;onPress:()=>void;disabled?:boolean;secondary?:boolean;busy?:boolean;danger?:boolean}) {return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled:disabled||busy,busy}} disabled={disabled||busy} onPress={onPress} style={({pressed})=>[styles.button,secondary&&styles.secondary,danger&&styles.danger,(disabled||busy)&&styles.disabled,pressed&&{opacity:.75}]}>{busy?<ActivityIndicator color={secondary?theme.primary:'#fff'}/>:<Text style={[styles.buttonText,secondary&&{color:theme.primary}]}>{label}</Text>}</Pressable>}
export function Toggle({label,help,value,onChange}:{label:string;help:string;value:boolean;onChange:(value:boolean)=>void}) {return <View style={styles.toggle}><View style={{flex:1,gap:5}}><Copy>{label}</Copy><Copy muted>{help}</Copy></View><Switch accessibilityLabel={label} value={value} onValueChange={onChange} trackColor={{true:theme.primary,false:theme.line}}/></View>}
export function Input(props:TextInputProps) {return <TextInput placeholderTextColor={theme.muted} {...props} style={[styles.input,props.style]}/>}
const styles=StyleSheet.create({copy:{fontSize:15,lineHeight:23,color:theme.ink},muted:{color:theme.muted},large:{fontSize:18,lineHeight:28},title:{fontSize:23,lineHeight:32,fontWeight:'700',color:theme.ink},card:{backgroundColor:theme.card,borderRadius:24,padding:22,gap:14,borderColor:theme.line,borderWidth:1},tint:{backgroundColor:theme.pale},button:{minHeight:50,padding:14,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:theme.primary},secondary:{backgroundColor:theme.pale},danger:{backgroundColor:theme.danger},disabled:{opacity:.45},buttonText:{fontSize:16,lineHeight:24,fontWeight:'600',color:'#fff',textAlign:'center'},toggle:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:8},input:{borderWidth:1,borderColor:theme.line,borderRadius:13,minHeight:52,padding:14,fontSize:16,color:theme.ink,backgroundColor:'#fff'}});
